INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (1, 'Bank');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (2, 'Building');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (3, 'Data Communication');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (4, 'Education');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (5, 'Farm');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (6, 'Health');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (7, 'Mining');
INSERT INTO CUSTOMER_TYPE (CUSTOMERTYPEID, customerTypeName) VALUES (8, 'Mining');

SELECT * FROM TB_CUSTOMER_TYPE;

